### PR TITLE
Issue 18 generate rsa keys

### PR DESCRIPTION
**Pull request by briandowns**

### CODE REVIEW

**Comment by bketelsen** [comment]
thanks can you rename the keys in the main.go functions that look for those keys?  it's looking for gc.rsa.pub and gc.rsa now I think

Awesome PR!

**Comment by briandowns** [comment]
I can change it there or in the Makefile.  Whatever you think would be best.

**Comment by bketelsen** [comment]
your choice sir.

**Comment by bketelsen** [comment]
you rock!

**Pull request merged**
